highlighter:      rouge
markdown:         kramdown

permalink:        pretty

include: [".well-known"]

plugins:
  - jemoji
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-seo-tag

title:            'Distillations'
description:      'A collection of posts on mathematics, human behavior, and engineering.'
url:              https://jasdev.me
baseurl:          /

author:
  name:           'Jasdev Singh'
  url:            https://jasdev.me
  email:          j@jasdev.me
  twitter:        jasdev

twitter:
  username:       jasdev
  url:            https://twitter.com/jasdev

collections:
  thoughts:
    output: true
    permalink: /:collection/:name
    defaults:
      values:
        layout: post
  notes:
    output: true
    permalink: /:collection/:name
    defaults:
      values:
        layout: post
