highlighter:      rouge
markdown:         kramdown

permalink:        pretty

include: [".well-known"]

plugins:
  - jemoji
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-seo-tag

title:            'Distillations'
description:      'A collection of posts on human behavior, technology, and engineering.'
url:              https://jasdev.me
baseurl:          /

author:
  name:           'Jasdev Singh'
  url:            https://jasdev.me
  email:          jasdev@jasdev.me
  twitter:        jasdev

twitter:
  username:       jasdev
  url:            https://twitter.com/jasdev

collections:
  thoughts:
    output: true
    permalink: /:collection/:name
    defaults:
      values:
        layout: post
  frp-ct-diary:
    output: true
    permalink: /:collection/:name
    defaults:
      values:
        layout: post


github:               https://github.com/jasdev
search:               https://duckduckgo.com/?q=site%3Ajasdev.me
gyroscope:            https://gyrosco.pe/jasdev/helix/
instagram:            https://instagram.com/jasdev
soundcloud:           https://soundcloud.com/jasdev-singh
